import { Category, Product, Brand, BlogPost, Order } from '@/types';

export const INITIAL_CATEGORIES: Category[] = [
  // --- LEVEL 1: ROOT CATEGORIES ---
  {
    id: 'cat-computers',
    name: 'Компьютеры и Ноутбуки',
    slug: 'computers-laptops',
    parentId: null,
    level: 1,
    icon: 'Laptop',
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop&q=80',
    description: 'Ноутбуки, комплектующие, рабочие станции и периферия',
    order: 1,
    featured: true,
  },
  {
    id: 'cat-smartphones',
    name: 'Смартфоны и Гаджеты',
    slug: 'smartphones-gadgets',
    parentId: null,
    level: 1,
    icon: 'Smartphone',
    image: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=800&auto=format&fit=crop&q=80',
    description: 'Флагманские смартфоны, планшеты, смарт-часы и аксессуары',
    order: 2,
    featured: true,
  },
  {
    id: 'cat-audio-tv',
    name: 'ТВ, Аудио и Видео',
    slug: 'tv-audio-video',
    parentId: null,
    level: 1,
    icon: 'Tv',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80',
    description: 'OLED телевизоры, Hi-Fi акустика, премиум наушники',
    order: 3,
    featured: true,
  },
  {
    id: 'cat-photo-video',
    name: 'Фото, Видео и Дроны',
    slug: 'photo-video-drones',
    parentId: null,
    level: 1,
    icon: 'Camera',
    image: 'https://images.unsplash.com/photo-1508614589041-895b88991e3e?w=800&auto=format&fit=crop&q=80',
    description: 'Камеры, квадрокоптеры DJI, стабилизаторы и оптика',
    order: 4,
    featured: true,
  },
  {
    id: 'cat-smart-home',
    name: 'Бытовая техника и Умный дом',
    slug: 'smart-home-appliances',
    parentId: null,
    level: 1,
    icon: 'Home',
    image: 'https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80',
    description: 'Пылесосы Dyson, роботы-пылесосы, кофемашины, климат',
    order: 5,
    featured: true,
  },
  {
    id: 'cat-gaming',
    name: 'Гейминг и Консоли',
    slug: 'gaming-consoles',
    parentId: null,
    level: 1,
    icon: 'Gamepad2',
    image: 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=800&auto=format&fit=crop&q=80',
    description: 'PlayStation 5, Xbox Series X, VR шлемы и геймерская мебель',
    order: 6,
    featured: true,
  },

  // --- LEVEL 2: COMPUTERS & LAPTOPS ---
  {
    id: 'sub-laptops',
    name: 'Ноутбуки',
    slug: 'laptops',
    parentId: 'cat-computers',
    level: 2,
    order: 1,
  },
  {
    id: 'sub-pc-parts',
    name: 'Комплектующие для ПК',
    slug: 'pc-components',
    parentId: 'cat-computers',
    level: 2,
    order: 2,
  },
  {
    id: 'sub-peripherals',
    name: 'Мониторы и Периферия',
    slug: 'peripherals',
    parentId: 'cat-computers',
    level: 2,
    order: 3,
  },

  // --- LEVEL 3: LAPTOPS SUB-SUBCATEGORIES ---
  {
    id: 'sub3-macbooks',
    name: 'Apple MacBook',
    slug: 'apple-macbook',
    parentId: 'sub-laptops',
    level: 3,
    order: 1,
  },
  {
    id: 'sub3-gaming-laptops',
    name: 'Игровые ноутбуки',
    slug: 'gaming-laptops',
    parentId: 'sub-laptops',
    level: 3,
    order: 2,
  },
  {
    id: 'sub3-ultrabooks',
    name: 'Ультрабуки для работы',
    slug: 'ultrabooks',
    parentId: 'sub-laptops',
    level: 3,
    order: 3,
  },

  // --- LEVEL 3: PC PARTS SUB-SUBCATEGORIES ---
  {
    id: 'sub3-gpus',
    name: 'Видеокарты (GPU)',
    slug: 'graphics-cards',
    parentId: 'sub-pc-parts',
    level: 3,
    order: 1,
  },
  {
    id: 'sub3-cpus',
    name: 'Процессоры (CPU)',
    slug: 'processors',
    parentId: 'sub-pc-parts',
    level: 3,
    order: 2,
  },
  {
    id: 'sub3-motherboards',
    name: 'Материнские платы',
    slug: 'motherboards',
    parentId: 'sub-pc-parts',
    level: 3,
    order: 3,
  },
  {
    id: 'sub3-ram-ssd',
    name: 'Память и SSD',
    slug: 'ram-and-ssd',
    parentId: 'sub-pc-parts',
    level: 3,
    order: 4,
  },

  // --- LEVEL 3: PERIPHERALS ---
  {
    id: 'sub3-monitors',
    name: 'Игровые и Проф. Мониторы',
    slug: 'monitors',
    parentId: 'sub-peripherals',
    level: 3,
    order: 1,
  },
  {
    id: 'sub3-keyboards',
    name: 'Механические клавиатуры',
    slug: 'mechanical-keyboards',
    parentId: 'sub-peripherals',
    level: 3,
    order: 2,
  },

  // --- LEVEL 2: SMARTPHONES ---
  {
    id: 'sub-smartphones-all',
    name: 'Смартфоны',
    slug: 'smartphones',
    parentId: 'cat-smartphones',
    level: 2,
    order: 1,
  },
  {
    id: 'sub-smartwatches',
    name: 'Смарт-часы и браслеты',
    slug: 'smartwatches',
    parentId: 'cat-smartphones',
    level: 2,
    order: 2,
  },
  {
    id: 'sub-tablets',
    name: 'Планшеты',
    slug: 'tablets',
    parentId: 'cat-smartphones',
    level: 2,
    order: 3,
  },

  // --- LEVEL 3: SMARTPHONES ---
  {
    id: 'sub3-iphone',
    name: 'Apple iPhone',
    slug: 'apple-iphone',
    parentId: 'sub-smartphones-all',
    level: 3,
    order: 1,
  },
  {
    id: 'sub3-samsung-phones',
    name: 'Samsung Galaxy',
    slug: 'samsung-galaxy',
    parentId: 'sub-smartphones-all',
    level: 3,
    order: 2,
  },
  {
    id: 'sub3-pixel-phones',
    name: 'Google Pixel',
    slug: 'google-pixel',
    parentId: 'sub-smartphones-all',
    level: 3,
    order: 3,
  },

  // --- LEVEL 2: AUDIO & TV ---
  {
    id: 'sub-headphones',
    name: 'Наушники и гарнитуры',
    slug: 'headphones',
    parentId: 'cat-audio-tv',
    level: 2,
    order: 1,
  },
  {
    id: 'sub-tvs',
    name: 'Телевизоры OLED / QLED',
    slug: 'televisions',
    parentId: 'cat-audio-tv',
    level: 2,
    order: 2,
  },
  {
    id: 'sub-soundbars',
    name: 'Акустика и Саундбары',
    slug: 'speakers-soundbars',
    parentId: 'cat-audio-tv',
    level: 2,
    order: 3,
  },

  // --- LEVEL 2: PHOTO & DRONES ---
  {
    id: 'sub-drones',
    name: 'Квадрокоптеры DJI',
    slug: 'dji-drones',
    parentId: 'cat-photo-video',
    level: 2,
    order: 1,
  },
  {
    id: 'sub-cameras',
    name: 'Беззеркальные камеры',
    slug: 'mirrorless-cameras',
    parentId: 'cat-photo-video',
    level: 2,
    order: 2,
  },

  // --- LEVEL 2: SMART HOME ---
  {
    id: 'sub-dyson-appliances',
    name: 'Техника Dyson',
    slug: 'dyson-tech',
    parentId: 'cat-smart-home',
    level: 2,
    order: 1,
  },
  {
    id: 'sub-robot-vacuums',
    name: 'Роботы-пылесосы',
    slug: 'robot-vacuums',
    parentId: 'cat-smart-home',
    level: 2,
    order: 2,
  },
  {
    id: 'sub-coffee-machines',
    name: 'Премиум Кофемашины',
    slug: 'coffee-machines',
    parentId: 'cat-smart-home',
    level: 2,
    order: 3,
  },

  // --- LEVEL 2: GAMING ---
  {
    id: 'sub-consoles',
    name: 'Игровые консоли',
    slug: 'consoles',
    parentId: 'cat-gaming',
    level: 2,
    order: 1,
  },
  {
    id: 'sub-vr-gear',
    name: 'VR шлемы и аксессуары',
    slug: 'vr-headsets',
    parentId: 'cat-gaming',
    level: 2,
    order: 2,
  },
];

export const INITIAL_BRANDS: Brand[] = [
  {
    id: 'brand-apple',
    name: 'Apple',
    slug: 'apple',
    logo: 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=300&auto=format&fit=crop&q=80',
    description: 'Инновационные компьютеры Mac, iPhone, iPad, часы Apple Watch и аудиотехника мирового уровня.',
    country: 'США',
    featured: true,
    productCount: 8,
  },
  {
    id: 'brand-asus',
    name: 'ASUS ROG',
    slug: 'asus-rog',
    logo: 'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=300&auto=format&fit=crop&q=80',
    description: 'Республика геймеров — бескомпромиссные ноутбуки, видеокарты и материнские платы для энтузиастов.',
    country: 'Тайвань',
    featured: true,
    productCount: 5,
  },
  {
    id: 'brand-sony',
    name: 'Sony',
    slug: 'sony',
    logo: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=300&auto=format&fit=crop&q=80',
    description: 'Легендарный звук, консоли PlayStation 5, камеры Alpha и премиальные OLED панели.',
    country: 'Япония',
    featured: true,
    productCount: 6,
  },
  {
    id: 'brand-samsung',
    name: 'Samsung',
    slug: 'samsung',
    logo: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=300&auto=format&fit=crop&q=80',
    description: 'Передовые смартфоны Galaxy Ultra, сверхбыстрые SSD и телевизоры Neo QLED.',
    country: 'Южная Корея',
    featured: true,
    productCount: 7,
  },
  {
    id: 'brand-dji',
    name: 'DJI',
    slug: 'dji',
    logo: 'https://images.unsplash.com/photo-1508614589041-895b88991e3e?w=300&auto=format&fit=crop&q=80',
    description: 'Мировой лидер в области гражданских квадрокоптеров и ручных стабилизаторов камеры.',
    country: 'Китай',
    featured: true,
    productCount: 3,
  },
  {
    id: 'brand-dyson',
    name: 'Dyson',
    slug: 'dyson',
    logo: 'https://images.unsplash.com/photo-1558002038-1055907df827?w=300&auto=format&fit=crop&q=80',
    description: 'Революционные беспроводные пылесосы, стайлеры Airwrap и очистители воздуха.',
    country: 'Великобритания',
    featured: true,
    productCount: 4,
  },
  {
    id: 'brand-keychron',
    name: 'Keychron',
    slug: 'keychron',
    logo: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=300&auto=format&fit=crop&q=80',
    description: 'Кастомные механические клавиатуры премиального уровня с беспроводным подключением.',
    country: 'Гонконг',
    featured: true,
    productCount: 3,
  },
  {
    id: 'brand-lg',
    name: 'LG Electronics',
    slug: 'lg',
    logo: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=300&auto=format&fit=crop&q=80',
    description: 'Эталонные OLED телевизоры с идеальным черным цветом и игровые дисплеи UltraGear.',
    country: 'Южная Корея',
    featured: true,
    productCount: 4,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-macbook-pro-16-m3-max',
    title: 'Apple MacBook Pro 16" (M3 Max, 36GB, 1TB SSD) Space Black',
    slug: 'apple-macbook-pro-16-m3-max-space-black',
    sku: 'HYK-APL-MBP16M3-SB',
    brand: 'Apple',
    categoryId: 'sub3-macbooks',
    categoryPath: [
      { id: 'cat-computers', name: 'Компьютеры и Ноутбуки', slug: 'computers-laptops' },
      { id: 'sub-laptops', name: 'Ноутбуки', slug: 'laptops' },
      { id: 'sub3-macbooks', name: 'Apple MacBook', slug: 'apple-macbook' },
    ],
    price: 9499,
    oldPrice: 10299,
    inStock: true,
    stockCount: 8,
    rating: 4.9,
    reviewCount: 24,
    isNew: true,
    isFeatured: true,
    isBestseller: true,
    images: [
      'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=1000&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=1000&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=1000&auto=format&fit=crop&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop&q=80',
    shortDescription: 'Флагманский 16-дюймовый ноутбук с процессором M3 Max, дисплеем Liquid Retina XDR 120Hz и до 22 часов автономной работы.',
    fullDescription: `MacBook Pro 16 с чипом M3 Max открывает невероятные горизонты производительности для разработчиков, 3D-аниматоров и видеомонтажеров.

Архитектура Apple Silicon нового поколения обеспечивает беспрецедентную вычислительную мощность GPU с поддержкой аппаратного ускорения трассировки лучей и Dynamic Caching. Дисплей Liquid Retina XDR с пиковой яркостью 1600 нит в HDR режиме дарит эталонную цветопередачу ProMotion.

- 14-ядерный CPU и 30-ядерный GPU (или 16/40)
- 36 GB объединенной памяти с пропускной способностью 300 ГБ/с
- Невероятная тишина и энергоэффективность даже под экстремальными нагрузками
- Аудиосистема из 6 динамиков с поддержкой Spatial Audio`,
    specGroups: [
      {
        group: 'Процессор и Графика',
        items: [
          { name: 'Процессор', value: 'Apple M3 Max (14 ядер: 10 производительных, 4 энергоэффективных)' },
          { name: 'Графика', value: 'Apple M3 Max 30-core GPU, Hardware Ray Tracing' },
          { name: 'Нейропроцессор', value: '16-core Neural Engine' },
        ],
      },
      {
        group: 'Дисплей',
        items: [
          { name: 'Диагональ', value: '16.2 дюйма' },
          { name: 'Тип матрицы', value: 'Liquid Retina XDR (Mini-LED)' },
          { name: 'Разрешение', value: '3456 x 2234 пикселей (254 ppi)' },
          { name: 'Частота обновления', value: 'До 120 Гц (ProMotion)' },
          { name: 'Яркость', value: '1000 нит (SDR/HDR), 1600 нит (пиковая HDR)' },
        ],
      },
      {
        group: 'Память и Накопитель',
        items: [
          { name: 'Оперативная память', value: '36 GB Unified Memory' },
          { name: 'SSD накопитель', value: '1 TB PCIe NVMe' },
        ],
      },
      {
        group: 'Корпус и Разъемы',
        items: [
          { name: 'Порты', value: '3x Thunderbolt 4 (USB-C), HDMI 2.1, SDXC card slot, MagSafe 3, 3.5mm Jack' },
          { name: 'Вес', value: '2.16 кг' },
          { name: 'Цвет', value: 'Space Black (Черный космос)' },
        ],
      },
    ],
    variants: [
      { id: 'v1', name: 'Space Black', type: 'color', value: '#1c1d1f' },
      { id: 'v2', name: 'Silver', type: 'color', value: '#e2e4e7' },
      { id: 'v3', name: '36GB RAM / 1TB SSD', type: 'storage', value: '36GB / 1TB' },
      { id: 'v4', name: '48GB RAM / 1TB SSD', type: 'storage', value: '48GB / 1TB', priceModifier: 1200 },
    ],
    warranty: '24 месяца официальной гарантии Apple',
    deliveryTime: 'Бесплатная доставка сегодня по Тбилиси',
    createdAt: '2026-09-01T10:00:00Z',
  },
  {
    id: 'prod-asus-rog-zephyrus-g16',
    title: 'ASUS ROG Zephyrus G16 (OLED 240Hz, Intel Core Ultra 9, RTX 4080, 32GB, 2TB) Eclipse Gray',
    slug: 'asus-rog-zephyrus-g16-gu605mz',
    sku: 'HYK-ASUS-G16-4080',
    brand: 'ASUS ROG',
    categoryId: 'sub3-gaming-laptops',
    categoryPath: [
      { id: 'cat-computers', name: 'Компьютеры и Ноутбуки', slug: 'computers-laptops' },
      { id: 'sub-laptops', name: 'Ноутбуки', slug: 'laptops' },
      { id: 'sub3-gaming-laptops', name: 'Игровые ноутбуки', slug: 'gaming-laptops' },
    ],
    price: 8699,
    oldPrice: 9199,
    inStock: true,
    stockCount: 5,
    rating: 4.8,
    reviewCount: 16,
    isNew: true,
    isFeatured: true,
    images: [
      'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=1000&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=1000&auto=format&fit=crop&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=800&auto=format&fit=crop&q=80',
    shortDescription: 'Ультратонкий цельнометаллический игровой ноутбук с первым в мире ROG Nebula OLED 240Hz 0.2ms дисплеем и видеокартой RTX 4080.',
    fullDescription: 'Zephyrus G16 переворачивает представление о портативных игровых станциях: цельный алюминиевый корпус толщиной всего 1.49 см, потрясающая матрица OLED с временем отклика 0.2 мс и бескомпромиссная мощь процессора Intel Core Ultra 9 и NVIDIA GeForce RTX 4080.',
    specGroups: [
      {
        group: 'Производительность',
        items: [
          { name: 'Процессор', value: 'Intel Core Ultra 9 185H (16 ядер, до 5.1 ГГц, с NPU)' },
          { name: 'Видеокарта', value: 'NVIDIA GeForce RTX 4080 Laptop GPU 12GB GDDR6' },
          { name: 'ОЗУ', value: '32 GB LPDDR5X 7467 MHz' },
          { name: 'Накопитель', value: '2 TB PCIe 4.0 NVMe SSD' },
        ],
      },
      {
        group: 'Экран',
        items: [
          { name: 'Диагональ и матрица', value: '16.0" ROG Nebula Display OLED 2.5K (2560 x 1600)' },
          { name: 'Частота и отклик', value: '240Hz, 0.2ms, G-Sync, 100% DCI-P3, VESA DisplayHDR True Black 500' },
        ],
      },
    ],
    warranty: '24 месяца гарантии производителя',
    deliveryTime: 'Доставка 1 день',
    createdAt: '2026-09-05T12:00:00Z',
  },
  {
    id: 'prod-iphone-16-pro-max',
    title: 'Apple iPhone 16 Pro Max 256GB Natural Titanium',
    slug: 'apple-iphone-16-pro-max-256gb-natural-titanium',
    sku: 'HYK-APL-IP16PM-256-NT',
    brand: 'Apple',
    categoryId: 'sub3-iphone',
    categoryPath: [
      { id: 'cat-smartphones', name: 'Смартфоны и Гаджеты', slug: 'smartphones-gadgets' },
      { id: 'sub-smartphones-all', name: 'Смартфоны', slug: 'smartphones' },
      { id: 'sub3-iphone', name: 'Apple iPhone', slug: 'apple-iphone' },
    ],
    price: 4399,
    oldPrice: 4699,
    inStock: true,
    stockCount: 14,
    rating: 5.0,
    reviewCount: 42,
    isNew: true,
    isFeatured: true,
    isBestseller: true,
    images: [
      'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=1000&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=1000&auto=format&fit=crop&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=800&auto=format&fit=crop&q=80',
    shortDescription: 'Флагман с чипом A18 Pro, кнопкой Camera Control, титановым корпусом 5-го класса и телеобъективом 5x тетрапризма.',
    fullDescription: 'iPhone 16 Pro Max создан для максимальных задач. Чип A18 Pro с поддержкой Apple Intelligence, увеличенный дисплей 6.9 дюйма Super Retina XDR с тончайшими рамками в истории Apple, съемка 4K 120 fps Dolby Vision и 4 студийных микрофона.',
    specGroups: [
      {
        group: 'Основные параметры',
        items: [
          { name: 'Процессор', value: 'Apple A18 Pro (3-нм архитектура)' },
          { name: 'Дисплей', value: '6.9" OLED Super Retina XDR, Always-On, 1-120Hz ProMotion' },
          { name: 'Встроенная память', value: '256 GB' },
          { name: 'Камеры', value: '48 Мп Fusion + 48 Мп Ультраширокая + 12 Мп Телевик 5x' },
        ],
      },
    ],
    variants: [
      { id: 'v-nt', name: 'Natural Titanium', type: 'color', value: '#a39b8b' },
      { id: 'v-dt', name: 'Desert Titanium', type: 'color', value: '#d4af37' },
      { id: 'v-bt', name: 'Black Titanium', type: 'color', value: '#2b2b2d' },
      { id: 'v-wt', name: 'White Titanium', type: 'color', value: '#f0f0f2' },
      { id: 'v-256', name: '256 GB', type: 'storage', value: '256GB' },
      { id: 'v-512', name: '512 GB', type: 'storage', value: '512GB', priceModifier: 700 },
      { id: 'v-1tb', name: '1 TB', type: 'storage', value: '1TB', priceModifier: 1500 },
    ],
    warranty: '12 месяцев официальной гарантии Apple',
    deliveryTime: 'Бесплатная экспресс-доставка сегодня',
    createdAt: '2026-09-10T08:00:00Z',
  },
  {
    id: 'prod-samsung-s24-ultra',
    title: 'Samsung Galaxy S24 Ultra 12GB/512GB Titanium Gray (Galaxy AI)',
    slug: 'samsung-galaxy-s24-ultra-512gb-gray',
    sku: 'HYK-SAM-S24U-512-TG',
    brand: 'Samsung',
    categoryId: 'sub3-samsung-phones',
    categoryPath: [
      { id: 'cat-smartphones', name: 'Смартфоны и Гаджеты', slug: 'smartphones-gadgets' },
      { id: 'sub-smartphones-all', name: 'Смартфоны', slug: 'smartphones' },
      { id: 'sub3-samsung-phones', name: 'Samsung Galaxy', slug: 'samsung-galaxy' },
    ],
    price: 3699,
    oldPrice: 3999,
    inStock: true,
    stockCount: 11,
    rating: 4.8,
    reviewCount: 31,
    isNew: false,
    isFeatured: true,
    isBestseller: true,
    images: [
      'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=1000&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=1000&auto=format&fit=crop&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&auto=format&fit=crop&q=80',
    shortDescription: 'Флагман со встроенным пером S-Pen, 200 Мп камерой, титановым корпусом и антибликовым стеклом Gorilla Armor.',
    fullDescription: 'Galaxy S24 Ultra задает высочайший стандарт среди Android-флагманов: плоский экран Dynamic AMOLED 2X с пиковой яркостью 2600 нит, мощнейший Snapdragon 8 Gen 3 for Galaxy и глубокая интеграция искусственного интеллекта Galaxy AI для синхронного перевода и редактирования фото.',
    specGroups: [
      {
        group: 'Характеристики',
        items: [
          { name: 'Процессор', value: 'Qualcomm Snapdragon 8 Gen 3 for Galaxy' },
          { name: 'Экран', value: '6.8" Dynamic AMOLED 2X QHD+ (3120x1440), 1-120Hz' },
          { name: 'Память', value: '12 GB RAM + 512 GB UFS 4.0' },
          { name: 'Камера', value: '200 Мп (OIS) + 50 Мп 5x перископ + 10 Мп 3x + 12 Мп ширик' },
        ],
      },
    ],
    warranty: '12 месяцев официальной гарантии Samsung',
    deliveryTime: 'Доставка сегодня',
    createdAt: '2026-08-20T10:00:00Z',
  },
  {
    id: 'prod-sony-wh1000xm5',
    title: 'Sony WH-1000XM5 Wireless Noise-Cancelling Headphones Silver',
    slug: 'sony-wh-1000xm5-wireless-silver',
    sku: 'HYK-SNY-WH1000XM5-SLV',
    brand: 'Sony',
    categoryId: 'sub-headphones',
    categoryPath: [
      { id: 'cat-audio-tv', name: 'ТВ, Аудио и Видео', slug: 'tv-audio-video' },
      { id: 'sub-headphones', name: 'Наушники и гарнитуры', slug: 'headphones' },
    ],
    price: 999,
    oldPrice: 1199,
    inStock: true,
    stockCount: 20,
    rating: 4.9,
    reviewCount: 56,
    isNew: false,
    isFeatured: true,
    isBestseller: true,
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=1000&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=1000&auto=format&fit=crop&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80',
    shortDescription: 'Лидер в активном шумоподавлении с двумя процессорами QN1 + V1, 8 микрофонами и автонастройкой звука.',
    fullDescription: 'Беспроводные наушники Sony WH-1000XM5 с инновационной системой шумоподавления Auto NC Optimizer, поддержкой Hi-Res Audio Wireless (кодек LDAC) и до 30 часов автономной работы с включенным ANC.',
    specGroups: [
      {
        group: 'Аудио и Связь',
        items: [
          { name: 'Драйвер', value: '30 мм купольный с диффузором из углеродного волокна' },
          { name: 'Частотный диапазон', value: '4 Гц – 40 000 Гц' },
          { name: 'Кодеки', value: 'LDAC, AAC, SBC' },
          { name: 'Автономность', value: 'До 30 часов с ANC, 40 часов без ANC' },
        ],
      },
    ],
    warranty: '12 месяцев гарантии Sony',
    deliveryTime: 'Бесплатная доставка',
    createdAt: '2026-08-15T14:00:00Z',
  },
  {
    id: 'prod-lg-oled-g4-65',
    title: 'LG OLED evo G4 65" 4K Smart TV (Gallery Edition, Alpha 11 AI, 144Hz)',
    slug: 'lg-oled-evo-g4-65-inch-4k-smart-tv',
    sku: 'HYK-LG-OLED65G4',
    brand: 'LG Electronics',
    categoryId: 'sub-tvs',
    categoryPath: [
      { id: 'cat-audio-tv', name: 'ТВ, Аудио и Видео', slug: 'tv-audio-video' },
      { id: 'sub-tvs', name: 'Телевизоры OLED / QLED', slug: 'televisions' },
    ],
    price: 6899,
    oldPrice: 7499,
    inStock: true,
    stockCount: 4,
    rating: 5.0,
    reviewCount: 9,
    isNew: true,
    isFeatured: true,
    images: [
      'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=1000&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1461151304267-38535e780c79?w=1000&auto=format&fit=crop&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800&auto=format&fit=crop&q=80',
    shortDescription: 'Флагманский телевизор OLED с технологией Brightness Booster Max (до 150% ярче), процессором Alpha 11 и креплением вплотную к стене.',
    fullDescription: 'LG OLED G4 — это вершина телевизионных технологий. Панель с микролинзами (MLA+) выдает беспрецедентную для органических светодиодов яркость. Идеально черный цвет, поддержка Dolby Vision, 4 порта HDMI 2.1 со скоростью 144 Гц и VRR для консолей и ПК.',
    specGroups: [
      {
        group: 'Экран и Видео',
        items: [
          { name: 'Диагональ', value: '65 дюймов (165 см)' },
          { name: 'Тип панели', value: 'OLED evo 4K Ultra HD (3840 x 2160)' },
          { name: 'Частота развертки', value: '144 Гц родная' },
          { name: 'Процессор', value: 'α11 AI Processor 4K' },
        ],
      },
    ],
    warranty: '5 лет гарантии на OLED панель',
    deliveryTime: 'Бесплатная доставка и установка в Тбилиси',
    createdAt: '2026-09-02T16:00:00Z',
  },
  {
    id: 'prod-dji-mini-4-pro',
    title: 'DJI Mini 4 Pro Fly More Combo (DJI RC 2 с экраном)',
    slug: 'dji-mini-4-pro-fly-more-combo-rc2',
    sku: 'HYK-DJI-MINI4P-FMC',
    brand: 'DJI',
    categoryId: 'sub-drones',
    categoryPath: [
      { id: 'cat-photo-video', name: 'Фото, Видео и Дроны', slug: 'photo-video-drones' },
      { id: 'sub-drones', name: 'Квадрокоптеры DJI', slug: 'dji-drones' },
    ],
    price: 3299,
    oldPrice: 3599,
    inStock: true,
    stockCount: 9,
    rating: 4.9,
    reviewCount: 22,
    isNew: false,
    isFeatured: true,
    isBestseller: true,
    images: [
      'https://images.unsplash.com/photo-1508614589041-895b88991e3e?w=1000&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=1000&auto=format&fit=crop&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1508614589041-895b88991e3e?w=800&auto=format&fit=crop&q=80',
    shortDescription: 'Легкий дрон до 249 грамм с всенаправленным распознаванием препятствий, 4K/60fps HDR видео и вертикальной съемкой.',
    fullDescription: 'DJI Mini 4 Pro — самый совершенный мини-дрон в мире. Благодаря сенсорам обзора на 360 градусов дрон полностью защищен от столкновений. Съемка в 10-бит D-Log M, передача видео DJI O4 до 20 км и до 34 минут полета на одном аккумуляторе.',
    specGroups: [
      {
        group: 'Полетные данные',
        items: [
          { name: 'Вес', value: '< 249 г (не требует регистрации во многих странах)' },
          { name: 'Дальность связи', value: 'До 20 км (O4 HD Video)' },
          { name: 'Время полета', value: 'До 34 мин (x3 батареи в комплекте)' },
          { name: 'Камера', value: '1/1.3" CMOS, f/1.7, 48 Мп, 4K/60fps HDR, 4K/100fps Slow-mo' },
        ],
      },
    ],
    warranty: '12 месяцев официальной гарантии DJI',
    deliveryTime: 'В наличии, доставка сегодня',
    createdAt: '2026-08-10T11:00:00Z',
  },
  {
    id: 'prod-dyson-v15-detect-absolute',
    title: 'Беспроводной пылесос Dyson V15 Detect Absolute Fluffy Gold',
    slug: 'dyson-v15-detect-absolute-gold',
    sku: 'HYK-DYS-V15-ABS',
    brand: 'Dyson',
    categoryId: 'sub-dyson-appliances',
    categoryPath: [
      { id: 'cat-smart-home', name: 'Бытовая техника и Умный дом', slug: 'smart-home-appliances' },
      { id: 'sub-dyson-appliances', name: 'Техника Dyson', slug: 'dyson-tech' },
    ],
    price: 2499,
    oldPrice: 2799,
    inStock: true,
    stockCount: 7,
    rating: 4.9,
    reviewCount: 38,
    isNew: false,
    isFeatured: true,
    isBestseller: true,
    images: [
      'https://images.unsplash.com/photo-1558002038-1055907df827?w=1000&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?w=1000&auto=format&fit=crop&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80',
    shortDescription: 'Мощнейший пылесос с лазерной подсветкой пыли, пьезодатчиком количества частиц и ЖК-дисплеем.',
    fullDescription: 'Dyson V15 Detect оснащен лазером Fluffy Optic, который делает невидимую пыль на твердом полу заметной. Пьезоэлектрический датчик измеряет и подсчитывает частицы пыли 15 000 раз в секунду, автоматически увеличивая мощность всасывания на коврах.',
    specGroups: [
      {
        group: 'Мощность и Питание',
        items: [
          { name: 'Мощность всасывания', value: '240 AW (Аэроватт)' },
          { name: 'Время работы', value: 'До 60 минут без потери мощности' },
          { name: 'Объем контейнера', value: '0.77 л с гигиеничной очисткой' },
          { name: 'Фильтрация', value: 'HEPA фильтрация 99.99% частиц до 0.3 микрон' },
        ],
      },
    ],
    warranty: '24 месяца гарантии Dyson',
    deliveryTime: 'Доставка курьером бесплатно',
    createdAt: '2026-08-25T15:00:00Z',
  },
  {
    id: 'prod-keychron-q1-pro',
    title: 'Механическая клавиатура Keychron Q1 Pro Wireless Custom (QMK/VIA, RGB) Carbon Black',
    slug: 'keychron-q1-pro-wireless-custom-carbon-black',
    sku: 'HYK-KCR-Q1PRO-KPB',
    brand: 'Keychron',
    categoryId: 'sub3-keyboards',
    categoryPath: [
      { id: 'cat-computers', name: 'Компьютеры и Ноутбуки', slug: 'computers-laptops' },
      { id: 'sub-peripherals', name: 'Мониторы и Периферия', slug: 'peripherals' },
      { id: 'sub3-keyboards', name: 'Механические клавиатуры', slug: 'mechanical-keyboards' },
    ],
    price: 649,
    oldPrice: 720,
    inStock: true,
    stockCount: 15,
    rating: 5.0,
    reviewCount: 19,
    isNew: true,
    isFeatured: true,
    images: [
      'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=1000&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=1000&auto=format&fit=crop&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=80',
    shortDescription: 'Кастомная 75% клавиатура в фрезерованном алюминиевом корпусе с креплением Double Gasket и поддержкой Bluetooth 5.1.',
    fullDescription: 'Keychron Q1 Pro — это ультимативная беспроводная клавиатура для программистов, писателей и ценителей безупречного звука тайпинга. Полностью настраивается через веб-конфигуратор VIA.',
    specGroups: [
      {
        group: 'Конструкция и Свичи',
        items: [
          { name: 'Форм-фактор', value: '75% (81 клавиша + программируемый энкодер)' },
          { name: 'Материал корпуса', value: 'Анодированный алюминий CNC 6063' },
          { name: 'Переключатели', value: 'Keychron K Pro Red (смазанные с завода)' },
          { name: 'Hot-Swap', value: 'Поддержка 3-pin и 5-pin MX свитчей' },
        ],
      },
    ],
    warranty: '12 месяцев гарантии',
    deliveryTime: 'В наличии',
    createdAt: '2026-09-08T09:00:00Z',
  },
  {
    id: 'prod-sony-playstation-5-slim',
    title: 'Игровая приставка Sony PlayStation 5 Slim 1TB Digital Edition + DualSense White',
    slug: 'sony-playstation-5-slim-1tb-digital',
    sku: 'HYK-SNY-PS5-SLM-DIG',
    brand: 'Sony',
    categoryId: 'sub-consoles',
    categoryPath: [
      { id: 'cat-gaming', name: 'Гейминг и Консоли', slug: 'gaming-consoles' },
      { id: 'sub-consoles', name: 'Игровые консоли', slug: 'consoles' },
    ],
    price: 1699,
    oldPrice: 1899,
    inStock: true,
    stockCount: 18,
    rating: 4.9,
    reviewCount: 64,
    isNew: false,
    isFeatured: true,
    isBestseller: true,
    images: [
      'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=1000&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=1000&auto=format&fit=crop&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=800&auto=format&fit=crop&q=80',
    shortDescription: 'Обновленная компактная консоль PS5 с 1TB сверхбыстрого SSD, поддержкой 4K 120Hz, Ray Tracing и звуком Tempest 3D.',
    fullDescription: 'PlayStation 5 Slim открывает новые игровые возможности, которые вы даже не могли себе представить. Ощутите молниеносную загрузку благодаря сверхскоростному накопителю SSD, глубокое погружение с тактильной обратной связью DualSense и адаптивными спусковыми курками.',
    specGroups: [
      {
        group: 'Спецификации',
        items: [
          { name: 'Процессор', value: 'AMD Zen 2 (8 ядер, 16 потоков до 3.5 ГГц)' },
          { name: 'Видеочип', value: 'AMD RDNA 2, 10.3 TFLOPS, Ray Tracing' },
          { name: 'Накопитель', value: '1 TB Ultra-High Speed NVMe SSD' },
          { name: 'Видеовыход', value: 'HDMI 2.1 (до 4K 120Hz, 8K, VRR)' },
        ],
      },
    ],
    warranty: '12 месяцев официальной гарантии Sony',
    deliveryTime: 'Доставка сегодня курьером',
    createdAt: '2026-08-01T12:00:00Z',
  },
  {
    id: 'prod-asus-rog-rtx-4090-strix',
    title: 'Видеокарта ASUS ROG Strix GeForce RTX 4090 OC Edition 24GB GDDR6X',
    slug: 'asus-rog-strix-geforce-rtx-4090-oc-24gb',
    sku: 'HYK-ASUS-RTX4090-OC',
    brand: 'ASUS ROG',
    categoryId: 'sub3-gpus',
    categoryPath: [
      { id: 'cat-computers', name: 'Компьютеры и Ноутбуки', slug: 'computers-laptops' },
      { id: 'sub-pc-parts', name: 'Комплектующие для ПК', slug: 'pc-components' },
      { id: 'sub3-gpus', name: 'Видеокарты (GPU)', slug: 'graphics-cards' },
    ],
    price: 6499,
    oldPrice: 6999,
    inStock: true,
    stockCount: 3,
    rating: 5.0,
    reviewCount: 14,
    isNew: false,
    isFeatured: true,
    images: [
      'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=1000&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1591488320449-011701bb6704?w=1000&auto=format&fit=crop&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1591488320449-011701bb6704?w=800&auto=format&fit=crop&q=80',
    shortDescription: 'Самая мощная видеокарта на планете с 24GB GDDR6X, массивной системой охлаждения и заводским разгоном.',
    fullDescription: 'ROG Strix GeForce RTX 4090 OC Edition переосмысливает концепцию бескомпромиссной игровой производительности и рендеринга. 16384 ядра CUDA, тензорные ядра 4-го поколения с DLSS 3.5 Frame Generation и премиальная печатная плата с 24-фазным питанием.',
    specGroups: [
      {
        group: 'Графический процессор',
        items: [
          { name: 'GPU', value: 'NVIDIA GeForce RTX 4090 (Ada Lovelace, 4nm)' },
          { name: 'CUDA ядра', value: '16 384' },
          { name: 'Видеопамять', value: '24 GB GDDR6X 384-bit 21 Gbps' },
          { name: 'Частота ядра (Boost)', value: '2640 MHz (OC Mode)' },
        ],
      },
    ],
    warranty: '36 месяцев гарантии ASUS',
    deliveryTime: 'Бесплатная курьерская доставка',
    createdAt: '2026-08-05T10:00:00Z',
  },
];

export const INITIAL_BLOG_POSTS: BlogPost[] = [
  {
    id: 'post-1',
    title: 'Большое сравнение: Apple M3 Max против топовых процессоров Intel и AMD в 2026 году',
    slug: 'apple-m3-max-vs-intel-amd-comparison',
    excerpt: 'Подробный тест в реальных рабочих задачах: рендеринг в Cinema 4D, компиляция масштабных проектов в Xcode и игры на максимальных настройках.',
    content: `Архитектура Apple Silicon продолжает эволюционировать с ошеломляющей скоростью. В этом обзоре эксперты Hykon.ge провели серию тестов на стенде с MacBook Pro 16" (M3 Max) и передовыми рабочими станциями на базе Intel Core Ultra 9 и AMD Ryzen 9.

### Энергоэффективность и температурный режим
Главный козырь M3 Max — это соотношение производительности на ватт мощности. В то время как ноутбуки на x86 архитектуре требуют подключения массивного блока питания на 330W для выдачи пиковых частот, MacBook Pro выдает 100% своей производительности даже при работе от аккумулятора в самолете или кафе.

### Тестирование в Blender и Unreal Engine 5
Благодаря аппаратной поддержке трассировки лучей (Hardware Ray Tracing) и технологии Dynamic Caching скорость отрисовки тяжелых сцен выросла на 75% по сравнению с поколением M2 Max.

### Итог
Для специалистов, работающих с тяжелым видео, музыкой и кодом, MacBook Pro остается непревзойденным эталоном мобильной рабочей станции.`,
    coverImage: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=1000&auto=format&fit=crop&q=80',
    author: {
      name: 'Ника Барамидзе',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
      role: 'Главный редактор раздела Tech',
    },
    date: '18 Сентября 2026',
    readTime: '6 мин чтения',
    category: 'Обзоры техники',
    tags: ['Apple', 'MacBook', 'Процессоры', 'Сравнение'],
    views: 1420,
  },
  {
    id: 'post-2',
    title: 'Как выбрать идеальный OLED телевизор: Разбираем технологии MLA, QD-OLED и частоты 144Hz',
    slug: 'how-to-choose-oled-tv-guide',
    excerpt: 'Гид покупателя: чем отличаются панели от LG и Samsung, стоит ли переплачивать за микролинзы MLA и как настроить идеальную картинку.',
    content: `Выбор телевизора премиального сегмента сегодня сводится к выбору между технологиями OLED evo с микролинзами (MLA+) и Quantum Dot OLED.

### В чем разница между LG OLED evo и QD-OLED?
Матрицы LG G4 используют микролинзовый массив, который фокусирует свет от органических диодов наружу, снижая потери яркости и нагрев. Результат — потрясающая пиковая яркость свыше 1500 нит на реальном контенте в формате Dolby Vision.

QD-OLED панели от Samsung предлагают более насыщенный синий и красный цветовой объем за счет квантовых точек.

### Что выбрать для PlayStation 5 и Xbox Series X?
Обратите внимание на наличие 4 портов HDMI 2.1 с полной пропускной способностью 48 Гбит/с, поддержку 120Hz/144Hz, Auto Low Latency Mode (ALLM) и переменной частоты кадров (VRR).`,
    coverImage: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=1000&auto=format&fit=crop&q=80',
    author: {
      name: 'Давид Квирикашвили',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
      role: 'Эксперт по аудио и ТВ',
    },
    date: '12 Сентября 2026',
    readTime: '8 мин чтения',
    category: 'Гиды и советы',
    tags: ['ТВ', 'LG', 'OLED', 'Гейминг'],
    views: 2890,
  },
  {
    id: 'post-3',
    title: 'Топ-5 беспроводных наушников с эталонным шумоподавлением в 2026 году',
    slug: 'top-5-wireless-anc-headphones-2026',
    excerpt: 'Мы протестировали Sony WH-1000XM5, Bose QuietComfort Ultra, Apple AirPods Max и Bowers & Wilkins Px7 S2e в условиях шумного мегаполиса и полетов.',
    content: `Современные флагманские наушники должны обладать тремя главными качествами: бескомпромиссным шумоподавлением, комфортной посадкой для многочасового прослушивания и поддержкой кодеков высокого разрешения.

1. **Sony WH-1000XM5** — безоговорочный лидер по балансу цены, адаптивного шумоподавления и микрофонов для звонков.
2. **Bose QC Ultra** — самый комфортный зажим оголовья и режим Immersive Audio.
3. **AirPods Max** — непревзойденные материалы корпуса из стали и сетки, идеальная экосистема с устройствами Apple.`,
    coverImage: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=1000&auto=format&fit=crop&q=80',
    author: {
      name: 'Ника Барамидзе',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
      role: 'Главный редактор',
    },
    date: '5 Сентября 2026',
    readTime: '5 мин чтения',
    category: 'Подборки',
    tags: ['Аудио', 'Наушники', 'Sony', 'Apple'],
    views: 3100,
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-1001',
    orderNumber: 'HYK-98241',
    customer: {
      fullName: 'Георгий Двали',
      phone: '+995 599 12 34 56',
      email: 'g.dvali@example.ge',
      city: 'Тбилиси',
      address: 'ул. Чавчавадзе 37, кв. 14',
      notes: 'Позвонить за 1 час до доставки',
    },
    deliveryMethod: 'courier',
    paymentMethod: 'card',
    items: [
      {
        productId: 'prod-macbook-pro-16-m3-max',
        productTitle: 'Apple MacBook Pro 16" (M3 Max, 36GB, 1TB SSD) Space Black',
        productSku: 'HYK-APL-MBP16M3-SB',
        image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400&auto=format&fit=crop&q=80',
        price: 9499,
        quantity: 1,
        selectedVariants: { color: 'Space Black', storage: '36GB / 1TB' },
      },
    ],
    subtotal: 9499,
    discount: 0,
    shippingFee: 0,
    total: 9499,
    status: 'processing',
    createdAt: '2026-09-25T14:20:00Z',
  },
  {
    id: 'ord-1002',
    orderNumber: 'HYK-98240',
    customer: {
      fullName: 'Мария Беридзе',
      phone: '+995 577 98 76 54',
      email: 'm.beridze@example.ge',
      city: 'Батуми',
      address: 'ул. Руставели 12, оф. 4',
    },
    deliveryMethod: 'courier',
    paymentMethod: 'installment',
    items: [
      {
        productId: 'prod-iphone-16-pro-max',
        productTitle: 'Apple iPhone 16 Pro Max 256GB Natural Titanium',
        productSku: 'HYK-APL-IP16PM-256-NT',
        image: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=400&auto=format&fit=crop&q=80',
        price: 4399,
        quantity: 1,
        selectedVariants: { color: 'Natural Titanium', storage: '256GB' },
      },
      {
        productId: 'prod-sony-wh1000xm5',
        productTitle: 'Sony WH-1000XM5 Wireless Noise-Cancelling Headphones Silver',
        productSku: 'HYK-SNY-WH1000XM5-SLV',
        image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&auto=format&fit=crop&q=80',
        price: 999,
        quantity: 1,
      },
    ],
    subtotal: 5398,
    discount: 100,
    shippingFee: 0,
    total: 5298,
    status: 'shipped',
    createdAt: '2026-09-24T18:10:00Z',
  },
];
